### ISSUE TITLE
持续下载超过5小时未完成

### ISSUE THREAD

**Issue by SkylineKID** [ACPudding/Osakabehime#1]
麻烦问下，Osakabehime下载日服资源现在显示进度到100%了依然有文件在下载，已经将近要下载了五六个小时了，请问这个是正常的情况吗？现在文件夹大概7.3G，是不是应该电脑开过夜让他下载了……

**Comment by ACPudding** [comment]
日服服务器国内不挂梯子是挺慢的，等右侧不走了就先关了吧。
如果感觉有漏的可以选“差异2”来补充。
进度条的问题我先记录一下，之前没出现过这个问题。

**Comment by SkylineKID** [comment]
好的，我再次尝试一下，谢谢！
